### PR TITLE
Add show_delta_file_sizes

### PR DESCRIPTION
**Pull request by robertkossendey**
Addresses #62

### CODE REVIEW

**Comment by MrPowers** [comment]
@robertkossendey - looks awesome, can you please add a little README description?

**Comment by robertkossendey** [comment]
@MrPowers will do - I knew I forgot something

**Comment by MrPowers** [comment]
@robertkossendey - just a friendly reminder to update the README, so we can get this one merged!

**Comment by robertkossendey** [comment]
@MrPowers updated the README, sorry! Been quite busy this week.

**Review by MrPowers — APPROVED** [review]

**Comment by MrPowers** [comment]
Thank you, merging!!

**Pull request merged**
