### PR TITLE
Adding drop_duplicate test

### PR DESCRIPTION
**Pull request by nkarpov**
I'm adding a failing test of drop_duplicates.

Test is failing for no columns provided. 

Error shows that the drop duplicates function does not preserve 1 of the duplicate rows (df1 is empty).

```
E           chispa.dataframe_comparer.DataFramesNotEqualError:
E           +------+-------------------------------------------+
E           | df1  |                    df2                    |
E           +------+-------------------------------------------+
E           | None | Row(col1=1, col2='A', col3='A', col4='C') |
E           +------+-------------------------------------------+
```

### CODE REVIEW

**Comment by MrPowers** [comment]
@robertkossendey - can you please take a look?

**Comment by MrPowers** [comment]
Merged this in.  Have an issue open to get this fixed: https://github.com/MrPowers/mack/issues/25

Thanks for reporting the bug @nkarpov

**Comment by souvik-databricks** [comment]
@MrPowers There is a test failure with this PR. 

@nkarpov Can you fix the unittest for this change

**Comment by MrPowers** [comment]
@souvik-databricks - I normally don't merge in changes that break test suites intentionally, but this is an exception because the test is correct and the code is broken.  It's good for the test suite to be failing if there is a bug in the code ;)

Here's the issue to get this fixed: https://github.com/MrPowers/mack/issues/25

Anyone can grab that issue and fix the bug 💪

**Pull request merged**
