### PR TITLE
Add notnull constraint append

### PR DESCRIPTION
**Pull request by cs23andris**
Added the feature to include NOT NULL constraint checks in the constraint_append function. issue number: https://github.com/MrPowers/mack/issues/100

Changes:

- Modified constraint_append function to include not null checks 
- Added unit test for not null testing
- Updated the README

Note: The feature is aiming to check NOT NULL constraints defined at the schema level and not as explicit table constraints. Explicit table constraints are already checked in the current version of the constraint_append function.

### CODE REVIEW

**Comment by cs23andris** [comment]
can you review @robertkossendey @MrPowers?

**Comment by robertkossendey** [comment]
@cs23andris @MrPowers LGTM

**Comment by robertkossendey** [comment]
@MrPowers can we merge this?

**Comment by MrPowers** [comment]
@cs23andris - sorry for the delay getting this merged.  Thank you for your contribution.

**Pull request merged**
