### PR TITLE
kB convert with 1024

### PR DESCRIPTION
**Pull request by betizad**
Conversion to human size should be with a factor of 1024 and not 1000.

### CODE REVIEW

**Comment by MrPowers** [comment]
@betizad - just following up with my previous comment.  If you have a second, can you please respond?

**Comment by betizad** [comment]
Thanks for the clarification. Indeed, I just realized that. 

manufacturers often use the term "kilobyte" to mean 1024 bytes (a kibibyte).

The helper function "humanize_bytes_binary" would be really appreciated.

**Comment by MrPowers** [comment]
@betizad - cool, would you like to submit a PR to add the `humanize_bytes_binary`.  We'd love to have your contribution.  If you don't want to add this that's alright too.  I'd also be happy to add it.  Thanks again for the valuable suggestion.

**Comment by betizad** [comment]
Sounds good. I'll send a PR.

**Comment by betizad** [comment]
@MrPowers The changes are pushed.

**Comment by robertkossendey** [comment]
@betizad the GitHub actions for black and flake8 are failing, could you make sure to run the pre-commits on your side before pushing?

**Comment by MrPowers** [comment]
@betizad - thanks for making the contribution.

**Pull request merged**
