### PR TITLE
Add latest_version functionality

### PR DESCRIPTION
**Pull request by danielbeach**
Add functionality for `latest_version`.
1. Update `README` to include new feature.
2. Add `latest_version` function.
3. Add unit test for `latest_version`.

### CODE REVIEW

**Comment by robertkossendey** [comment]
LGTM!

**Review by jaceklaskowski — APPROVED** [review]
LGTM

**Review by robertkossendey — APPROVED** [review]

**Review by MrPowers — APPROVED** [review]

**Comment by MrPowers** [comment]
This is great, thank you for the contribution @danielbeach 🚀

**Comment by robertkossendey** [comment]
@MrPowers flake8 and black are failing. Could we add the functionality that checks run on PR as well?

**Comment by MrPowers** [comment]
@robertkossendey - yes, [looks like you added that here](https://github.com/MrPowers/mack/commit/521b9fc8d5ac8a1a10a446a7a981d6cc705be8de), but feel free to open an issue if this still needs more attention.

**Comment by robertkossendey** [comment]
@MrPowers I will fix the failing checks

**Comment by MrPowers** [comment]
@robertkossendey - ok, thank you

**Pull request merged**
