### PR TITLE
Add is unique col method

### PR DESCRIPTION
**Pull request by robertkossendey**
This PR adds the is_unique_col method, mentioned in #30 .
@MrPowers WDYT about the naming? Currently it does not implicate that you can provide a set of columns, but I am struggling to find a good name..

### CODE REVIEW

**Comment by MrPowers** [comment]
@robertkossendey - perhaps `is_composite_key` would be a better name for this function?

Can you do some digging into the "official database terms" like compound key, natural key, surrogate key, etc?  Hopefully we can align all the function names with standard relational database nomenclature.

**Comment by robertkossendey** [comment]
@MrPowers will do 👍 we could consider to have a dictionary / glossary explaining those terms. Could be helpful for mack users.

**Comment by MrPowers** [comment]
@robertkossendey - yea, I dictionary explaining those terms in the README would be a really good idea.  That's something I'd refer to often as well 🙈

**Comment by robertkossendey** [comment]
@MrPowers will add this later to this PR 👍🏼👍🏼

**Comment by robertkossendey** [comment]
@MrPowers updated the PR.

**Pull request merged**
